wheel cache

diff --git a/.github/workflows/ci_linux.yml b/.github/workflows/ci_linux.yml
--- a/.github/workflows/ci_linux.yml
+++ b/.github/workflows/ci_linux.yml
@@ -56,8 +56,10 @@ jobs:
 
       - name: Install apt packages
         run: |
-          sudo apt-get install -t bionic/universe libatlas-base-dev gfortran libsqlite3-dev sqlite3 libcurl4-openssl-dev libgeos-dev libexpat1-dev libspatialite-dev libxml2-dev libfreexl-dev libzstd-dev
-          apt list --installed | grep 'libatlas-base-dev\|gfortran\|libsqlite3-dev\|sqlite3\|libcurl4-openssl-dev\|libgeos-dev\|libexpat1-dev\|libspatialite-dev\|libxml2-dev\|libfreexl-dev\|libzstd-dev' > $GITHUB_WORKSPACE/apt_list
+          sudo apt-get install libatlas-base-dev libcurl4-openssl-dev libgeos-dev libfreexl-dev libzstd-dev libspatialite-dev
+          # Packages not included in the standard ubuntu repositories (e.g. bionic/universe or bionic/main) could change
+          # API version and should be included in the following list
+          apt list --installed | grep 'libgeos-dev\|libxml2-dev' > $GITHUB_WORKSPACE/apt_list
           cat $GITHUB_WORKSPACE/apt_list
 
       - name: Dependency Cache
@@ -66,49 +68,60 @@ jobs:
           path: gdalinstall
           key: ${{ runner.os }}-gdal-${{ matrix.config.GDALVERSION }}-proj-${{ matrix.config.PROJVERSION }}-${{ hashFiles('**/apt_list') }}
 
-      - name: Install Python dependencies
-        run: |
-          python -m pip install -U pip wheel
-          python -m pip install -r requirements-ci.txt
-          python -m pip wheel -r requirements-dev.txt
-          python -m pip install -r requirements-dev.txt
+      - name: Cache pip
+        uses: actions/cache@v2
+        with:
+          # This path is specific to Ubuntu
+          path: ~/.cache/pip
+          # Look to see if there is a cache hit for the corresponding requirements file
+          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
+            ${{ runner.os }}-
 
-      - name: Build PROJ
-        run: |
-          source $GITHUB_WORKSPACE/env_variables
-          chmod +x scripts/travis_proj_install.sh && ./scripts/travis_proj_install.sh
+        - name: Install Python dependencies
+          run: |
+            python -m pip install -U pip wheel
+            python -m pip install -r requirements-ci.txt
+            python -m pip wheel -r requirements-dev.txt
+            python -m pip install -r requirements-dev.txt
 
-      - name: Install FileGDB
-        run: |
-          source $GITHUB_WORKSPACE/env_variables
-          chmod +x scripts/travis_filegdb_install.sh && ./scripts/travis_filegdb_install.sh
+        - name: Build PROJ
+          run: |
+            source $GITHUB_WORKSPACE/env_variables
+            chmod +x scripts/travis_proj_install.sh && ./scripts/travis_proj_install.sh
 
-      - name: Build GDAL
-        run: |
-          source $GITHUB_WORKSPACE/env_variables
-          chmod +x scripts/travis_gdal_install.sh && ./scripts/travis_gdal_install.sh
-          gdal-config --version
+        - name: Install FileGDB
+          run: |
+            source $GITHUB_WORKSPACE/env_variables
+            chmod +x scripts/travis_filegdb_install.sh && ./scripts/travis_filegdb_install.sh
 
-      - name: Build Fiona
-        run: |
-          source $GITHUB_WORKSPACE/env_variables
-          if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $($GDALINST/gdal-$GDALVERSION/bin/gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
-          GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install --no-deps --force-reinstall --no-use-pep517 -e .
+        - name: Build GDAL
+          run: |
+            source $GITHUB_WORKSPACE/env_variables
+            chmod +x scripts/travis_gdal_install.sh && ./scripts/travis_gdal_install.sh
+            gdal-config --version
 
-      - name: Print Environment
-        run: |
-          source $GITHUB_WORKSPACE/env_variables
-          python -m pip freeze
-          fio --version
-          fio --gdal-version
-          python -c "import fiona; fiona.show_versions()"
+        - name: Build Fiona
+          run: |
+            source $GITHUB_WORKSPACE/env_variables
+            if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $($GDALINST/gdal-$GDALVERSION/bin/gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
+            GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install --no-deps --force-reinstall --no-use-pep517 -e .
 
-      - name: Test with pytest
-        run: |
-          source $GITHUB_WORKSPACE/env_variables
-          python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
+        - name: Print Environment
+          run: |
+            source $GITHUB_WORKSPACE/env_variables
+            python -m pip freeze
+            fio --version
+            fio --gdal-version
+            python -c "import fiona; fiona.show_versions()"
 
-      - name: Coveralls
-        run: coveralls || echo "!! intermittent coveralls failure"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        - name: Test with pytest
+          run: |
+            source $GITHUB_WORKSPACE/env_variables
+            python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
+
+        - name: Coveralls
+          run: coveralls || echo "!! intermittent coveralls failure"
+          env:
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
