home

diff --git a/.github/workflows/ci_macos.yml b/.github/workflows/ci_macos.yml
--- a/.github/workflows/ci_macos.yml
+++ b/.github/workflows/ci_macos.yml
@@ -44,6 +44,7 @@ jobs:
         
     - name: Build GDAL
       run: |
+        echo $HOME
         export GDALVERSION=${{matrix.config.GDALVERSION}}
         export PROJVERSION=${{matrix.config.PROJVERSION}}
         export PATH=$GDALINST/gdal-$GDALVERSION/bin:$GDALINST/proj-$PROJVERSION/bin:$PATH
@@ -56,14 +57,14 @@ jobs:
         export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj
         gdal-config --version
 
-    - name: Build Fiona
-      run: |
-        if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $($GDALINST/gdal-$GDALVERSION/bin/gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
-        GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install -v -v -v --no-deps --force-reinstall --no-use-pep517 -e .
-        fio --version
-        fio --gdal-version
+    #- name: Build Fiona
+      #run: |
+        #if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $($GDALINST/gdal-$GDALVERSION/bin/gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
+        #GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install -v -v -v --no-deps --force-reinstall --no-use-pep517 -e .
+        #fio --version
+        #fio --gdal-version
 
-    - name: Test with pytest
-      run: |
-        python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
+    #- name: Test with pytest
+      #run: |
+        #python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
 
