use brew list for cache

diff --git a/.github/workflows/ci_macos.yml b/.github/workflows/ci_macos.yml
--- a/.github/workflows/ci_macos.yml
+++ b/.github/workflows/ci_macos.yml
@@ -54,47 +54,45 @@ jobs:
 
       - name: Install brew packages
         run: |
-          #brew install pkg-config@0.29.2_3 expat@2.2.9 libspatialite@4.3.0a_8 sqlite@3.32.1 geos@3.8.1_1
-          brew search geos@
-          brew install pkg-config expat libspatialite sqlite geos@3.8.1
-          brew list --versions
+          brew install pkg-config expat libspatialite sqlite geos
+          brew list --versions > $HOME/brew_list
 
-#      - name: Install Python dependencies
-#        run: |
-#          python -m pip install --upgrade pip
-#          python -m pip install -r requirements-dev.txt
-#          python -m pip install coveralls>=1.1 --upgrade
-#
-#      - name: Dependency Cache
-#        uses: actions/cache@v2
-#        env:
-#          cache-name: cache-gdal
-#        with:
-#          path: $HOME/gdalinstall
-#          key: ${{ runner.os }}-gdal-${{ matrix.config.GDALVERSION }}-proj-${{ matrix.config.PROJVERSION }}
-#
-#      - name: Build PROJ
-#        run: |
-#          source $HOME/env_variables
-#          chmod +x scripts/travis_proj_install.sh && ./scripts/travis_proj_install.sh
-#
-#      - name: Build GDAL
-#        run: |
-#          source $HOME/env_variables
-#          ls -l $GDALINST
-#          chmod +x scripts/travis_gdal_install.sh && ./scripts/travis_gdal_install.sh
-#          gdal-config --version
-#
-#      - name: Build Fiona
-#        run: |
-#          source $HOME/env_variables
-#          if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $($GDALINST/gdal-$GDALVERSION/bin/gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
-#          GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install -v -v -v --no-deps --force-reinstall --no-use-pep517 -e .
-#          fio --version
-#          fio --gdal-version
-#
-#
-#      - name: Test with pytest
-#        run: |
-#          source $HOME/env_variables
-#          python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install -r requirements-dev.txt
+          python -m pip install coveralls>=1.1 --upgrade
+
+      - name: Dependency Cache
+        uses: actions/cache@v2
+        env:
+          cache-name: cache-gdal
+        with:
+          path: $HOME/gdalinstall
+          key: ${{ runner.os }}-gdal-${{ matrix.config.GDALVERSION }}-proj-${{ matrix.config.PROJVERSION }}-${{ hashFiles('$HOME/brew_list') }}
+
+      - name: Build PROJ
+        run: |
+          source $HOME/env_variables
+          chmod +x scripts/travis_proj_install.sh && ./scripts/travis_proj_install.sh
+
+      - name: Build GDAL
+        run: |
+          source $HOME/env_variables
+          ls -l $GDALINST
+          chmod +x scripts/travis_gdal_install.sh && ./scripts/travis_gdal_install.sh
+          gdal-config --version
+
+      - name: Build Fiona
+        run: |
+          source $HOME/env_variables
+          if [ "$GDALVERSION" = "master" ]; then echo "Using gdal master"; elif [ $($GDALINST/gdal-$GDALVERSION/bin/gdal-config --version) == $(sed 's/[a-zA-Z].*//g' <<< $GDALVERSION) ]; then echo "Using gdal $GDALVERSION"; else echo "NOT using gdal $GDALVERSION as expected; aborting"; exit 1; fi
+          GDAL_CONFIG=$GDALINST/gdal-$GDALVERSION/bin/gdal-config python -m pip install -v -v -v --no-deps --force-reinstall --no-use-pep517 -e .
+          fio --version
+          fio --gdal-version
+
+
+      - name: Test with pytest
+        run: |
+          source $HOME/env_variables
+          python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
