add pytest

diff --git a/.github/workflows/ci_windows.yml b/.github/workflows/ci_windows.yml
--- a/.github/workflows/ci_windows.yml
+++ b/.github/workflows/ci_windows.yml
@@ -31,7 +31,15 @@ jobs:
       - name: Set env variables
         run: |
           echo "C:\\gdal\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+
           echo "GDAL_DATA=C:\\gdal\\bin\\gdal-data" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
+          $env:GDAL_VERSION -gt '3.0.0' ? echo "PROJ_LIB=C:\\gdal\\bin\\proj6\\share" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
+
+          echo "$GITHUB_PATH"
+          echo $env:GITHUB_PATH
+          echo ""
+          echo "$GITHUB_ENV"
+          echo $env:GITHUB_ENV
 
       - name: Add msbuild to PATH
         uses: microsoft/setup-msbuild@v1.0.2
@@ -51,17 +59,36 @@ jobs:
           python -m pip wheel -r requirements-dev.txt
           python -m pip install -r requirements-dev.txt
 
+      - name: Build Fiona
+        continue-on-error: ${{ matrix.GDALVERSION == 'master' }}
+        run: |
+          python -m pip install --install-option=build_ext --install-option="-IC:\gdal\include" --install-option="-lgdal_i" --install-option="-LC:\gdal\lib" --no-deps --force-reinstall --no-use-pep517 -e .
+
       - name: Print Environment
         continue-on-error: ${{ matrix.GDALVERSION == 'master' }}
         run: |
           echo "python -m pip freeze"
           python -m pip freeze
 
-          echo %PATH%
+          echo ""
+          echo "fio --version"
+          fio --version
 
-      - name: Build Fiona
+          echo ""
+          echo "fio --gdal-version"
+          fio --gdal-version
+
+          echo ""
+          echo "python -c \"import fiona; fiona.show_versions()\""
+          python -c "import fiona; fiona.show_versions()"
+
+      - name: pytest
         continue-on-error: ${{ matrix.GDALVERSION == 'master' }}
         run: |
-          python -m pip install --install-option=build_ext --install-option="-IC:\gdal\include" --install-option="-lgdal_i" --install-option="-LC:\gdal\lib" --no-deps --force-reinstall --no-use-pep517 -e .
+          python -m pytest -m "not wheel" --cov fiona --cov-report term-missing
 
-
+      - name: Coveralls
+        continue-on-error: ${{ matrix.GDALVERSION == 'master' }}
+        run: coveralls || echo "!! intermittent coveralls failure"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
